### ISSUE TITLE
Dependency on github.com/blakeembrey/router#router-engine

### ISSUE THREAD

**Issue by BTMPL** [mulesoft-labs/osprey-router#11]
We're trying to use the osprey-mock-service in a gated environment with no git access and our deploy is failing at connecting to github to fetch blakeembrey/router#router-engine

Is there a reason this is using a fork of https://github.com/pillarjs/router (which is in npm, and is one path release in front of the fork)?

**Comment by BTMPL** [comment]
As an alternative, is it possible to publish the dependency into npm, so our local proxy (Artifactory) can request and cache it?

**Comment by sichvoge** [comment]
Seems that @blakeembrey fork adds implementing a custom router that is necessary for osprey https://github.com/blakeembrey/router/tree/router-engine#implementing-your-own-router

**Comment by jstoiko** [comment]
@BTMPL: is there a way to tell Artifactory to cache a package that is hosted on github? I find it off that it wouldn't...

**Comment by BTMPL** [comment]
@jstoiko I was able to work around that - this was caused by a couple of things: outdated Artifactory, wrong config and lack of github.com access (firewall). 

So if there's no need for this from others, I will close this topic :)

**Comment by cdierkens** [comment]
@BTMPL I'm having the exact same issue. We have a closed environment that only has access to NPM packages through an Artifactory NPM registry, and are unable to install through github style urls. What was your workaround?

**Comment by BTMPL** [comment]
@cdierkens sorry, in our case access to github.com hosted code was finally allowed, though it turned out git ignored credentials not stored in c:\users\username\.git which made it not use the proxy in the first place :(

**Comment by cdierkens** [comment]
@BTMPL Yeah, I think our solve is going to have to be a little more deep than that unfortunately.

We could fork and publish our own with a scope:

1. osprey
2. osprey-router
3. blakeembrey/router#router-engine

Or

We could have Artifactory act as a proxy for github (but this would be seen as a security concern)
https://www.jfrog.com/confluence/display/RTF/Remote+Repositories

Or

Unless @blakeembrey can publish his router under a [scope](https://docs.npmjs.com/misc/scope), and this repo can point to that scoped NPM package.
