### ISSUE TITLE
Dependency on github.com/blakeembrey/router#router-engine

### ISSUE THREAD

**Issue by cdierkens** [mulesoft-labs/osprey-router#13]
This dependency blocks the ability to run in a CI/CD build, as a github style URLs attempt to git clone a dependency, instead of pulling from an NPM registry.

We have a closed environment that only has access to NPM packages through an Artifactory NPM registry.

The registry caches npmjs registry for anything not found in the private registry.
Any package can be published to the private registry.
Hitting URLs outside of the internal registry is not allowed.

**Comment by warroyo** [comment]
@blakeembrey any chance this can be updated I have the same issue mentioned above.

**Comment by blakeembrey** [comment]
I no longer work at MuleSoft and do not have access. I won't be able to help, sorry.

**Comment by sichvoge** [comment]
@cdierkens @warroyo Sorry for my stupidity, but what do you want us to do here?

**Comment by warroyo** [comment]
@sichvoge in this line https://github.com/mulesoft-labs/osprey-router/blob/master/package.json#L36 the dependency is directly referencing github, so instead of going to npm to get the package it is trying to clone. This causes a problem when you do not have access to the internet and you use something like artifactory to  proxy packages. We are suggesting that the above line be changed to use npm instead. for example:

````
"router":"^1.3.1"
````

**Comment by cdierkens** [comment]
Blakes fork isn't published to npm, so you'll need to fork his changes and
publish under a scope, something like @mulesoft/router.

**Comment by warroyo** [comment]
@cdierkens so in the readme https://github.com/blakeembrey/router/blob/master/README.md, under installation,  this is just left over from the fork?

**Comment by cdierkens** [comment]
In github you can compare forks against the origin, although I'm sure the
diff is huge and hard to comb through.

**Comment by blakeembrey** [comment]
The diff should be pretty straightforward. It's really just two PRs in a commit: https://github.com/blakeembrey/router/commit/cfe18f9d59adca65c24c9c951ebd43e9bf07937e. Both are open PRs, one has been merged but the other is still a bit undecided: https://github.com/pillarjs/router/pull/30 and https://github.com/pillarjs/router/pull/29. Getting the path functionality plugin-able is the one still open, but I can re-submit a cleaner PR that implements the same functionality again and land that in the PillarJS router sooner so we can have an official release. /cc @dougwilson, are you ok with that?

**Comment by fedotov** [comment]
I see quite big difference between https://github.com/blakeembrey/router/ and https://github.com/pillarjs/router
And osprey-router a bit extends blakeembrey/router.
So why not include blakeembrey/router/ into osprey-router? Will that breach npm policy?

**Comment by cdierkens** [comment]
FWIW: This is still an issue, except you are pointing to an internal package. Why you don't just publish an npm package is beyond me.

Closing because this is beyond stale.
