### ISSUE TITLE
Cut a new version

### ISSUE THREAD

**Issue by samcday** [mulesoft-labs/osprey-router#3]
Hello, would you be able to cut a new version of this lib and bump the dep in `osprey` itself? I need a release that has PR #2 in it :)

**Comment by blakeembrey** [comment]
No worries. I forgot about that issue. Got to keep a mental note of using short urls from now on.

**Comment by blakeembrey** [comment]
All updated :+1:

**Comment by samcday** [comment]
Thanks! :smiley:
